- name: DB settings -- check for valid variables/settings
  fail:
    msg: "Invalid settings! Check the following variables: `leihs_external_hostname` and `leihs_external_base_url`"
  when: >
    (leihs_external_hostname is not defined) or (leihs_external_hostname is none)
    or (leihs_external_base_url == "https://")

- name: DB settings -- set external_base_url
  shell: |
    PGPASSWORD={{database.password}} psql --port {{database.port}} --dbname {{database.database}} --username {{database.username}} -c \
      "UPDATE system_and_security_settings SET external_base_url='{{ leihs_external_base_url }}' WHERE id=0;"
  become: True
  become_user: "{{database.username}}"