# Minimal defaults for independent role execution
# When used in playbook, values from main defaults will override these
LEIHS_ROOT_DIR: "/leihs"
leihs_my_user: 'leihs-my'
leihs_my_dir: "{{LEIHS_ROOT_DIR}}/my"
