# TODO: Check hardcoded path (uses LEIHS_ROOT_DIR which defaults to /leihs)
- file:
    path: "{{LEIHS_ROOT_DIR}}/config"
    state: directory
  name: make sure {{LEIHS_ROOT_DIR}}/config exists

- file:
    path: "{{item}}"
    state: absent
  name: clean up old {{ item }}
  with_items:
  - "{{LEIHS_ROOT_DIR}}/config/master-secret.txt"
  - /etc/systemd/system/leihs_create-master-secret.path
  - /etc/systemd/system/leihs_create-master-secret.service

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
